### ISSUE TITLE
Tutorial step 1 - getting started with Carbon React

### ISSUE THREAD

**Issue by kellychurchill** [carbon-design-system/developer-essentials#1]
_Lab goal - getting an app running locally with a component and use of Design System has been demystified_

**Comment by kellychurchill** [comment]
## Lab Outline 

- Carbon ecosystem overview, how this is different than IBM's other attempts at "One UI" frameworks, available implementations, how they consume elements, how design kit and implementations share same vocabulary through tokens and component naming, etc.
- Introduce dev essentials courses, and what we're building together
- Fork > clone > checkout branch > see failing tests on empty create-react-app
- Install carbon packages
- Sass build
- Hello Carbon component
- Introduce test stack and see failing test
- UI shell component, accessibility considerations
- React router to navigate among pages
- Make sure all tests pass
- PR process, submit PR

**Comment by mattrosno** [comment]
Possible process:

1. Build it locally including final tests
1. Create and publish `step-1` branch to `carbon-tutorial` that includes end of step 1 Sketch file and tests (do not merge into master)
1. Create and publish `tutorial-1` branch to `carbon-website` that includes instructions for building step 1 (do not merge into master)

**Comment by mattrosno** [comment]
![image](https://user-images.githubusercontent.com/1691245/56905929-da1c3180-6a66-11e9-93e8-9ffb1e67bc6e.png)

Tutorial step 1 can live here.

**Comment by mattrosno** [comment]
@aledavila @jnm2377 when you create the remote branch in `carbon-tutorial`, can you name it `react-step-1`? So our branching strategy could extend to an angular tutorial, vue tutorial, etc. in the future?
