### ISSUE TITLE
Tutorial step 3 - populating components using APIs

### ISSUE THREAD

**Issue by kellychurchill** [carbon-design-system/developer-essentials#3]
_Lab Goal - understanding how to use Carbon Design System to build a modern layered architecture_

**Comment by kellychurchill** [comment]
## Lab Outline

- Make sure carbon-tutorial repo has been forked, cloned, with tutorial step 3 branch checked out
- Consume API(s) to populate static pages build in previous tutorial step
- Empty states / loading states / skeletons / time outs
- Possibly consume data via GraphQL?
- Make sure all tests pass, submit PR

**Comment by vpicone** [comment]
Looking forward to this. I think the thrust of the lesson should revolve around Carbon specific loading topics. If we use a simple loading library like axios with a mock API we'll be able to dive deeper into topics/components unique to Carbon.

I'd be happy to do an "advanced" section using a GraphQL loading library like Apollo, but as part of the core lesson it would add a fair amount of overhead and detract from the main (Carbon specific) content.

@kellychurchill when can we expect the repo to be ready?

**Comment by kellychurchill** [comment]
Thanks @vpicone! According to the development timeline: https://github.com/carbon-design-system/developer-essentials/blob/master/README.md, it should be approximately april 26
