### ISSUE TITLE
Tutorial repository

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/developer-essentials#6]
Would be nice to have a `carbon-tutorial` repo that participants fork and clone with a branch for each lab.

* Each tutorial step has a branch that comes initialized with failing tests
* Circle CI (or something similar) so participant PRs can be passing or failing
* Netlify (or something similar) so participant PRs can be previewed
* Kelly and team review PRs to verify course completion (add comment "thanks for completing!" but don't merge participant PRs - closed them instead)

**Comment by joshblack** [comment]
Initial PR: https://github.com/carbon-design-system/carbon-tutorial/pull/1

Covers:

- CircleCI
- Netlify
- Blank project scaffold with Create React App
