### ISSUE TITLE
Tutorial information architecture

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/developer-essentials#7]
Where does the tutorial live in the Carbon website?

If we're planning on a 5 step tutorial now, how can we set it up to have more advanced steps in the future?

With this initial tutorial being React, how do we plan on having sibling tutorials for vanilla, Angular, Vue, etc. in the future?

What's the high-level thing that's getting built (e.g. IBM Tacos)?

Do we want to plan on having design tutorials to create the thing in Sketch that's getting built in this tutorial series? (Future effort.)

**Comment by designertyler** [comment]
@mattrosno Is there a draft or outline you can link to that shows the information that needs to be shown on the site?

What's the roadmap for the more advanced steps, other frameworks, and design tutorials?

**Comment by mattrosno** [comment]
@designertyler https://github.com/carbon-design-system/developer-essentials/blob/master/README.md#dates developer tutorial step 1 live by 5/28, all 5 steps live by 6/25.

I don't know of any immediate commitments/plans to do a design tutorial. Same goes for sibling Angular or Vue tutorials. Ideally it'd be great to let those teams contribute if they'd like to. Which means we'd have a logical place to house those sibling developer tutorials.

No immediate plans to do advanced tutorials (step 6 and beyond), although I'd expect us to add advanced steps through v11.

**Comment by mattrosno** [comment]
@designertyler FYI looking to have these page titles.

![image](https://user-images.githubusercontent.com/1691245/57084894-c0762680-6cc0-11e9-996b-1211aaf55cd8.png)

**Comment by mattrosno** [comment]
![image](https://user-images.githubusercontent.com/1691245/57088131-3da49a00-6cc7-11e9-8a9e-e499bf7934a4.png)

In `navigation.json`:

```json
  "tutorial": {
    "title": "Tutorial",
    "sub-nav": {
      "overview": {
        "title": "Introduction"
      },
      "react-step-1": {
        "title": "1. Installing Carbon"
      },
      "react-step-2": {
        "title": "2. Building pages"
      },
      "react-step-3": {
        "title": "3. Using APIs"
      },
      "react-step-4": {
        "title": "4. Creating components"
      },
      "react-step-5": {
        "title": "5. Deploying to IBM Cloud"
      }
    }
  },
```
