### ISSUE TITLE
Tutorial prerequisites

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/developer-essentials#8]
Prior to the first lab, email the registrants to share prerequisites.

- Going to be using React
- If you want to learn React basics, here are good articles/courses/etc.
- We'll be using public GitHub - make sure to have an account and here is how you optionally link GHE and GH accounts

**Comment by vpicone** [comment]
**Github**: If you're new to Github, make sure you've [made an account](https://github.com/join), and try out their [getting started guide](https://guides.github.com/activities/hello-world/) to get a feel for interacting with a github repository.

**ES6/ES2015**: React apps often use the latest and greatest from JavaScript (ES6/ES2015). You'll want to be up to speed on the most commonly used features added to the language. [Let's Learn ES6](https://www.youtube.com/playlist?list=PL57atfCFqj2h5fpdZD-doGEIs0NZxeJTX) covers those features in depth.

**React**: If you're just getting started with React, the official React documentation is incredible. If you enjoy learning-by-doing check out their [intro tutorial](https://reactjs.org/tutorial/tutorial.html). You'll want to supplement that with their [step-by-step guide](https://reactjs.org/docs/hello-world.html), especially if you prefer learning concepts by reading. _These two resources go great together._

Checklist:
- [x] [Github](https://guides.github.com/activities/hello-world/)
- [x] [ES6](https://www.youtube.com/playlist?list=PL57atfCFqj2h5fpdZD-doGEIs0NZxeJTX)
- [x] [React learn-by-reading](https://reactjs.org/tutorial/tutorial.html)
- [x] [React learn-by-doing](https://reactjs.org/docs/hello-world.html)

**Comment by kellychurchill** [comment]
@vpicone and @mattrosno - when do you want to send out these prerequisites to registrants?

**Comment by vpicone** [comment]
@kellychurchill I'd say ASAP. We can always add more prereqs as folks right their content, but these are pretty essential to doing any of the course.

**Comment by kellychurchill** [comment]
@mattrosno will have the content ready to share with participants by 5/13. We will send an email to all participants with this info.

**Comment by kellychurchill** [comment]
Hey @mattrosno this was closed but I haven't seen the content that I should share with the participants. Can you point me to it?

**Comment by mattrosno** [comment]
https://www.carbondesignsystem.com/tutorial/overview/ is live but not linked in nav yet.

Connor and I are working on this now. We can get the Medium article done today if you want to distribute that?

https://github.com/carbon-design-system/developer-essentials/issues/11
