### ISSUE TITLE
Revised Lab Content

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/developer-essentials#9]
# Development timeline (draft)

1. 4/26
    * Tutorial design
    * `carbon-repo`
    * `carbon-website` content strategy
1. 5/1 Lab 1
1. 5/6 Lab 2
1. 5/8 Lab 3
1. 5/13 Lab 4
1. 5/16 Lab 5

# Format

* Each lab is a tutorial step that we make available in `carbon-website` the day prior
* We have `carbon-tutorial` repo published, and also day prior we publish a new branch for each tutorial step
  * Tutorial repo is configured with Netlify, test runner, and Circle CI
  * The branches act as a starting point for if somebody missed the first lab, etc.
  * The branches also are seeded with failing tests
  * To verify lab completion, participants submit PR that they can view Netlify preview link and CI verifies passing tests
  * Kelly and team review PRs and comment then close instead of merging participant PRs
* Each tutorial should take an hour or two to complete
* Those responsible for each tutorial step will introduce it (10-15 talk) at the broadcasted FED@IBM events

# Website & tutorial content

* Dev: **Matt**
* Design: 
* Content: **Connor**

# Tutorial repo

* Dev: **Josh**
* Dev: **Josefina**

# Lab 1

* Dev: **Josefina**
* Dev: **Ale**
* Carbon ecosystem overview, how this is different than IBM's other attempts at "One UI" frameworks, available implementations, how they consume elements, how design kit and implementations share same vocabulary through tokens and component naming, etc.
* Introduce dev essentials courses, and what we're building together
* Fork > clone > checkout branch > see failing tests on empty create-react-app
* Install carbon packages
* Sass build
* Hello Carbon component
* Introduce test stack and see failing test
* UI shell component, accessibility considerations
* React router to navigate among pages
* Make sure all tests pass
* PR process, submit PR

# Lab 2

* Dev: **Andrew**
* Dev: **Josefina**
* Make sure `carbon-tutorial` repo has been forked, cloned, with tutorial step 2 branch checked out
* Deep dive on grid, layout, icons, themes, icons, colors... "tokens"
* Build out UI shell pages with diverse page types that require different grids and components (dashboard page, data-heavy page, marketing page)
* All static pages, but focus is on using elements and components in detail with accessibility best practices along the way
* Make sure all tests pass, submit PR

# Lab 3

* Dev: **Vince**
* Dev: **D.A.**
* Make sure `carbon-tutorial` repo has been forked, cloned, with tutorial step 3 branch checked out
* Consume API(s) to populate static pages build in previous tutorial step
* Empty states / loading states / skeletons / time outs
* Possibly consume data via GraphQL?
* Make sure all tests pass, submit PR

# Lab 4

* Dev: **Audrey**
* Dev: **D.A.**
* Make sure `carbon-tutorial` repo has been forked, cloned, with tutorial step 4 branch checked out
* Create new component that's specific to our tutorial using Carbon assets and best practices
* Write tests for new component
* Go through accessibility checklist to walk through accessibility considerations
* Make sure all tests pass, submit PR

# Lab 5

* Dev: **Alison**
* Dev: **TJ**
* Make sure `carbon-tutorial` repo has been forked, cloned, with tutorial step 5 branch checked out
* Deploy to IBM Cloud
* Go over a few build performance enhancements now that the app is in a production environment instead of development environment (optimizing builds, minification, maybe even React SSR?)
* Make sure all tests pass, submit PR with link to deployed app
* Final call to action on what contribution process looks like and how to stay engaged in the Carbon ecosystem

**Comment by kellychurchill** [comment]
- [x] Update README to reflect revised content
- [x] Update w3.ibm.com/design/essentials to reflect revised content
- [x] Update Your Learning link to reflect revised content 
- [x] Update lab issues and assign to responsible devs
